spring.application.name=empreendimentos

spring.datasource.url=jdbc:postgresql://postgres:ja3XFWHvwQ31dU2Y@db.hfntskpezergrtwzoxfj.supabase.co:5432/postgres

spring.datasource.username=postgres

spring.datasource.password=ja3XFWHvwQ31dU2Y

spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=9VXZ8ZJEKYGWBFMO5C0XKT0FT63580TF
jwt.expiration-minutes=60